### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by dsmit192** [dsmit192/BMI-Calculator#10]
Users should only be able to input valid numbers into the form. 

For example a user cannot be 300 cm or 200 kg.

**Comment by maxime-dl** [comment]
Almost done  : 
I think this gives an error, but I don't know whats the reason.( maybe the type)
---mainactivity.cs----
  String m = editHeight.Text;
                int h = int.Parse(m);

**Comment by dsmit192** [comment]
I took a look at this and made a new branch. I think we are going to have to do an asynchronous process to handle this properly.

**Comment by dsmit192** [comment]
ported to Unity application
